<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNTuioL9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNTuioL9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNTuioL9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNTuioL9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNTuioL9\App_KernelDevDebugContainer([
    'container.build_hash' => 'NTuioL9',
    'container.build_id' => 'b2b88e76',
    'container.build_time' => 1621003408,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNTuioL9');
